//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consumir.ServicioSegip {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carnetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primerapellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundoapellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechanacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadocivilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string carnet {
            get {
                return this.carnetField;
            }
            set {
                if ((object.ReferenceEquals(this.carnetField, value) != true)) {
                    this.carnetField = value;
                    this.RaisePropertyChanged("carnet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string primerapellido {
            get {
                return this.primerapellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primerapellidoField, value) != true)) {
                    this.primerapellidoField = value;
                    this.RaisePropertyChanged("primerapellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string segundoapellido {
            get {
                return this.segundoapellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundoapellidoField, value) != true)) {
                    this.segundoapellidoField = value;
                    this.RaisePropertyChanged("segundoapellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fechanacimiento {
            get {
                return this.fechanacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.fechanacimientoField, value) != true)) {
                    this.fechanacimientoField = value;
                    this.RaisePropertyChanged("fechanacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string estadocivil {
            get {
                return this.estadocivilField;
            }
            set {
                if ((object.ReferenceEquals(this.estadocivilField, value) != true)) {
                    this.estadocivilField = value;
                    this.RaisePropertyChanged("estadocivil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resultado", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Resultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool coincidecarnetField;
        
        private bool coincidenombresField;
        
        private bool coincideprimerapellidoField;
        
        private bool coincidesegundoapellidoField;
        
        private bool coincidefechanacimientoField;
        
        private bool coincidesexoField;
        
        private bool coincideestadocivilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool coincidecarnet {
            get {
                return this.coincidecarnetField;
            }
            set {
                if ((this.coincidecarnetField.Equals(value) != true)) {
                    this.coincidecarnetField = value;
                    this.RaisePropertyChanged("coincidecarnet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool coincidenombres {
            get {
                return this.coincidenombresField;
            }
            set {
                if ((this.coincidenombresField.Equals(value) != true)) {
                    this.coincidenombresField = value;
                    this.RaisePropertyChanged("coincidenombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool coincideprimerapellido {
            get {
                return this.coincideprimerapellidoField;
            }
            set {
                if ((this.coincideprimerapellidoField.Equals(value) != true)) {
                    this.coincideprimerapellidoField = value;
                    this.RaisePropertyChanged("coincideprimerapellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool coincidesegundoapellido {
            get {
                return this.coincidesegundoapellidoField;
            }
            set {
                if ((this.coincidesegundoapellidoField.Equals(value) != true)) {
                    this.coincidesegundoapellidoField = value;
                    this.RaisePropertyChanged("coincidesegundoapellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool coincidefechanacimiento {
            get {
                return this.coincidefechanacimientoField;
            }
            set {
                if ((this.coincidefechanacimientoField.Equals(value) != true)) {
                    this.coincidefechanacimientoField = value;
                    this.RaisePropertyChanged("coincidefechanacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool coincidesexo {
            get {
                return this.coincidesexoField;
            }
            set {
                if ((this.coincidesexoField.Equals(value) != true)) {
                    this.coincidesexoField = value;
                    this.RaisePropertyChanged("coincidesexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool coincideestadocivil {
            get {
                return this.coincideestadocivilField;
            }
            set {
                if ((this.coincideestadocivilField.Equals(value) != true)) {
                    this.coincideestadocivilField = value;
                    this.RaisePropertyChanged("coincideestadocivil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioSegip.wsSegipSoap")]
    public interface wsSegipSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        Consumir.ServicioSegip.ObtenerDatosResponse ObtenerDatos(Consumir.ServicioSegip.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumir.ServicioSegip.ObtenerDatosResponse> ObtenerDatosAsync(Consumir.ServicioSegip.ObtenerDatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento carnet del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ComprobarDatos", ReplyAction="*")]
        Consumir.ServicioSegip.ComprobarDatosResponse ComprobarDatos(Consumir.ServicioSegip.ComprobarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ComprobarDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumir.ServicioSegip.ComprobarDatosResponse> ComprobarDatosAsync(Consumir.ServicioSegip.ComprobarDatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatos", Namespace="http://tempuri.org/", Order=0)]
        public Consumir.ServicioSegip.ObtenerDatosRequestBody Body;
        
        public ObtenerDatosRequest() {
        }
        
        public ObtenerDatosRequest(Consumir.ServicioSegip.ObtenerDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public ObtenerDatosRequestBody() {
        }
        
        public ObtenerDatosRequestBody(string CI) {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumir.ServicioSegip.ObtenerDatosResponseBody Body;
        
        public ObtenerDatosResponse() {
        }
        
        public ObtenerDatosResponse(Consumir.ServicioSegip.ObtenerDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Consumir.ServicioSegip.Persona ObtenerDatosResult;
        
        public ObtenerDatosResponseBody() {
        }
        
        public ObtenerDatosResponseBody(Consumir.ServicioSegip.Persona ObtenerDatosResult) {
            this.ObtenerDatosResult = ObtenerDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprobarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprobarDatos", Namespace="http://tempuri.org/", Order=0)]
        public Consumir.ServicioSegip.ComprobarDatosRequestBody Body;
        
        public ComprobarDatosRequest() {
        }
        
        public ComprobarDatosRequest(Consumir.ServicioSegip.ComprobarDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ComprobarDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string carnet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string primerapellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string segundoapellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fechanacimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sexo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string estadocivil;
        
        public ComprobarDatosRequestBody() {
        }
        
        public ComprobarDatosRequestBody(string carnet, string nombres, string primerapellido, string segundoapellido, string fechanacimiento, string sexo, string estadocivil) {
            this.carnet = carnet;
            this.nombres = nombres;
            this.primerapellido = primerapellido;
            this.segundoapellido = segundoapellido;
            this.fechanacimiento = fechanacimiento;
            this.sexo = sexo;
            this.estadocivil = estadocivil;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprobarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComprobarDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumir.ServicioSegip.ComprobarDatosResponseBody Body;
        
        public ComprobarDatosResponse() {
        }
        
        public ComprobarDatosResponse(Consumir.ServicioSegip.ComprobarDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ComprobarDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Consumir.ServicioSegip.Resultado ComprobarDatosResult;
        
        public ComprobarDatosResponseBody() {
        }
        
        public ComprobarDatosResponseBody(Consumir.ServicioSegip.Resultado ComprobarDatosResult) {
            this.ComprobarDatosResult = ComprobarDatosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsSegipSoapChannel : Consumir.ServicioSegip.wsSegipSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsSegipSoapClient : System.ServiceModel.ClientBase<Consumir.ServicioSegip.wsSegipSoap>, Consumir.ServicioSegip.wsSegipSoap {
        
        public wsSegipSoapClient() {
        }
        
        public wsSegipSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsSegipSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSegipSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSegipSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumir.ServicioSegip.ObtenerDatosResponse Consumir.ServicioSegip.wsSegipSoap.ObtenerDatos(Consumir.ServicioSegip.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatos(request);
        }
        
        public Consumir.ServicioSegip.Persona ObtenerDatos(string CI) {
            Consumir.ServicioSegip.ObtenerDatosRequest inValue = new Consumir.ServicioSegip.ObtenerDatosRequest();
            inValue.Body = new Consumir.ServicioSegip.ObtenerDatosRequestBody();
            inValue.Body.CI = CI;
            Consumir.ServicioSegip.ObtenerDatosResponse retVal = ((Consumir.ServicioSegip.wsSegipSoap)(this)).ObtenerDatos(inValue);
            return retVal.Body.ObtenerDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumir.ServicioSegip.ObtenerDatosResponse> Consumir.ServicioSegip.wsSegipSoap.ObtenerDatosAsync(Consumir.ServicioSegip.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumir.ServicioSegip.ObtenerDatosResponse> ObtenerDatosAsync(string CI) {
            Consumir.ServicioSegip.ObtenerDatosRequest inValue = new Consumir.ServicioSegip.ObtenerDatosRequest();
            inValue.Body = new Consumir.ServicioSegip.ObtenerDatosRequestBody();
            inValue.Body.CI = CI;
            return ((Consumir.ServicioSegip.wsSegipSoap)(this)).ObtenerDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumir.ServicioSegip.ComprobarDatosResponse Consumir.ServicioSegip.wsSegipSoap.ComprobarDatos(Consumir.ServicioSegip.ComprobarDatosRequest request) {
            return base.Channel.ComprobarDatos(request);
        }
        
        public Consumir.ServicioSegip.Resultado ComprobarDatos(string carnet, string nombres, string primerapellido, string segundoapellido, string fechanacimiento, string sexo, string estadocivil) {
            Consumir.ServicioSegip.ComprobarDatosRequest inValue = new Consumir.ServicioSegip.ComprobarDatosRequest();
            inValue.Body = new Consumir.ServicioSegip.ComprobarDatosRequestBody();
            inValue.Body.carnet = carnet;
            inValue.Body.nombres = nombres;
            inValue.Body.primerapellido = primerapellido;
            inValue.Body.segundoapellido = segundoapellido;
            inValue.Body.fechanacimiento = fechanacimiento;
            inValue.Body.sexo = sexo;
            inValue.Body.estadocivil = estadocivil;
            Consumir.ServicioSegip.ComprobarDatosResponse retVal = ((Consumir.ServicioSegip.wsSegipSoap)(this)).ComprobarDatos(inValue);
            return retVal.Body.ComprobarDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumir.ServicioSegip.ComprobarDatosResponse> Consumir.ServicioSegip.wsSegipSoap.ComprobarDatosAsync(Consumir.ServicioSegip.ComprobarDatosRequest request) {
            return base.Channel.ComprobarDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumir.ServicioSegip.ComprobarDatosResponse> ComprobarDatosAsync(string carnet, string nombres, string primerapellido, string segundoapellido, string fechanacimiento, string sexo, string estadocivil) {
            Consumir.ServicioSegip.ComprobarDatosRequest inValue = new Consumir.ServicioSegip.ComprobarDatosRequest();
            inValue.Body = new Consumir.ServicioSegip.ComprobarDatosRequestBody();
            inValue.Body.carnet = carnet;
            inValue.Body.nombres = nombres;
            inValue.Body.primerapellido = primerapellido;
            inValue.Body.segundoapellido = segundoapellido;
            inValue.Body.fechanacimiento = fechanacimiento;
            inValue.Body.sexo = sexo;
            inValue.Body.estadocivil = estadocivil;
            return ((Consumir.ServicioSegip.wsSegipSoap)(this)).ComprobarDatosAsync(inValue);
        }
    }
}
